dist: xenial
language: python

matrix:
    fast_finish: true
    include:
      - { python: "2.7", env: DJANGO_VERSION=1.10 }
      - { python: "2.7", env: DJANGO_VERSION=1.11 }

      - { python: "3.5", env: DJANGO_VERSION=1.10 }
      - { python: "3.5", env: DJANGO_VERSION=1.11 }
      - { python: "3.5", env: DJANGO_VERSION=2.0 }
      - { python: "3.5", env: DJANGO_VERSION=2.1 }

      - { python: "3.6", env: DJANGO_VERSION=1.10 }
      - { python: "3.6", env: DJANGO_VERSION=1.11 }
      - { python: "3.6", env: DJANGO_VERSION=2.0 }
      - { python: "3.6", env: DJANGO_VERSION=2.1 }

      - { python: "3.7", env: DJANGO_VERSION=2.0 }
      - { python: "3.7", env: DJANGO_VERSION=2.1 }
      - { python: "3.7", env: DJANGO_VERSION=2.2 }

install:
  - pip install -r requirements/test.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - coverage run --source=django_google_maps manage.py test
  - coverage report --show-missing
  - flake8 django_google_maps --max-line-length=120 --max-complexity=4
