language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements/test.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - coverage run --source=django_google_maps manage.py test
  - coverage report --show-missing
  - flake8 django_google_maps --max-line-length=120 --max-complexity=4

env:
  - DJANGO_VERSION=2.0.1
